name: Main workflow
on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Shortcut client
        uses: ./.github/actions/setup
    
      - name: Formatting check
        uses: actions-rs/cargo@v1
        with:
            command: fmt
            args: -p shortcut_release_helper -- --check

      - name: Build
        uses: actions-rs/cargo@v1
        with:
            command: build
